In [257]:
import h5py
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from functools import reduce

In [258]:
DATASET_PATH = 'uci_ml_hackathon_fire_dataset_2012-05-09_2013-01-01_10k_train.hdf5'

with h5py.File(DATASET_PATH, 'r') as f:
    train_data = {}
    for k in list(f):
        train_data[k] = f[k][:]
        
print(train_data)

{'datetime': array([1336558800000000000, 1336593660000000000, 1336599660000000000, ...,
       1356685800000000000, 1356862380000000000, 1356988440000000000],
      dtype=int64), 'land_cover': array([[[[-1.000000e+00, -1.000000e+00, -1.000000e+00, ...,
          -1.000000e+00, -6.560000e-02, -1.000000e+00],
         [-1.000000e+00, -1.000000e+00, -1.000000e+00, ...,
           2.986080e+01,  4.180960e+01,  3.426400e+01],
         [-1.000000e+00, -1.000000e+00, -1.000000e+00, ...,
           2.757920e+01,  5.965920e+01,  5.832800e+01],
         ...,
         [          nan,           nan,           nan, ...,
                    nan,           nan,           nan],
         [          nan,           nan,           nan, ...,
                    nan,           nan,           nan],
         [          nan,           nan,           nan, ...,
                    nan,           nan,           nan]],

        [[ 0.000000e+00,  0.000000e+00,  0.000000e+00, ...,
           0.000000e+00,  0.000000e

In [259]:
print(train_data.keys())

dict_keys(['datetime', 'land_cover', 'latitude', 'longitude', 'meteorology', 'observed', 'target'])


In [260]:
print("Land Cover", train_data['land_cover'].shape)
print("Data point", train_data['land_cover'][90].shape)
print("Layer", train_data['land_cover'][90][0].shape)
print(train_data['land_cover'][90][0][0])

Land Cover (10000, 17, 30, 30)
Data point (17, 30, 30)
Layer (30, 30)
[168.7616  61.3024  46.1248  27.0816  20.3264  36.0032  22.8304  17.7424
  -0.6672  -1.      -1.      -1.      -1.      70.4176 151.3568 232.5408
 200.9072 232.7952 257.72   223.3456 202.288  218.1216 165.6752 162.5168
 118.1056 216.5888 192.552  105.9312 119.2976 146.4848]


In [261]:
train_data['land_cover'][0].reshape(17,-1).shape

(17, 900)

In [262]:
print("Land Cover", train_data['land_cover'].shape)
print(train_data['land_cover'][0][0])
print("Data point", train_data['land_cover'][1000].shape)
print("Layer", train_data['land_cover'][1000][10].shape)
#print(train_data['land_cover'][1000][10])
summ = 0
for i in range(6, 16):
    summ += train_data['land_cover'][1000][i]
#print(summ)

Land Cover (10000, 17, 30, 30)
[[-1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00 -1.00000000e+00  4.89440012e+00 -1.00000000e+00
  -6.56000003e-02 -1.00000000e+00]
 [-1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
  -1.00000000e+00 -1.00000000e+00 -1.00000000e+00  2.98607998e+01
   4.18096

In [385]:
train = pd.DataFrame()

In [628]:

# df_aspect = pd.DataFrame()
# df_canopydensity = pd.DataFrame()
# df_canopybaseheight = pd.DataFrame()
# df_canopycover = pd.DataFrame()
# df_canopyHeight = pd.DataFrame()
# df_elevation = pd.DataFrame()
# df_slope = pd.DataFrame()
# df_observed_48 = pd.DataFrame()
# df_observed_36 = pd.DataFrame()
# df_observed_24 = pd.DataFrame()
# df_observed_12 = pd.DataFrame()
# df_observed_0 = pd.DataFrame()
# df_target_12 = pd.DataFrame()
# df_datetime = pd.DataFrame()
# df_latitude = pd.DataFrame()
# df_longitude = pd.DataFrame()

aspect = list()
canopydensity = list()
canopybaseheight = list()
canopycover = list()
canopyHeight = list()
elevation = list()
slope = list()
observed_48 = list()
observed_36 = list()
observed_24 = list()
observed_12 = list()
observed_0 = list()
target_12 = list()
datetime = list()
latitude = list()
longitude = list()

for i in range(10000):
#     aspect.append(train_data['land_cover'][i][0])
#     canopydensity.append(train_data['land_cover'][i][1])
#     canopybaseheight.append(train_data['land_cover'][i][2])
#     canopycover.append(train_data['land_cover'][i][3])
#     canopyHeight.append(train_data['land_cover'][i][4])
#     elevation.append(train_data['land_cover'][i][5])
#     slope.append(train_data['land_cover'][i][16])
    observed_48.append(train_data['observed'][i][4])
    observed_36.append(train_data['observed'][i][3])
    observed_24.append(train_data['observed'][i][2])
    observed_12.append(train_data['observed'][i][1])
    observed_0.append(train_data['observed'][i][0])
    #datetime.append(train_data['land_cover'][i][2])


#aspect, canopydensity, canopybaseheight, canopycover, canopyHeight, elevation, slope, 
X = np.stack((observed_48, observed_36, observed_24, observed_12, observed_0))
X = np.rollaxis(X, 1, 0)  
print(X.shape)

X[np.isnan(X)] = np.median(X[~np.isnan(X)])
#np.all(np.isfinite(X_train))
#print(aspect[0])
#print(canopydensity[0])


#     df_observed_48 = df_observed_48.append({'Observed-48':np.array(train_data['observed'][i].reshape(5,-1)[4])}, ignore_index=True)
#     df_observed_36 = df_observed_36.append({'Observed-36':np.array(train_data['observed'][i].reshape(5,-1)[3])}, ignore_index=True)
#     df_observed_24 = df_observed_24.append({'Observed-24':np.array(train_data['observed'][i].reshape(5,-1)[2])}, ignore_index=True)
#     df_observed_12 = df_observed_12.append({'Observed-12':np.array(train_data['observed'][i].reshape(5,-1)[1])}, ignore_index=True)
#     df_observed_0 = df_observed_0.append({'Observed-0':np.array(train_data['observed'][i].reshape(5,-1)[0])}, ignore_index=True)

#print(aspect)

(10000, 5, 30, 30)


In [621]:
print(train_data['target'][1170][0])

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0

In [622]:
# df_datetime, df_latitude, df_longitude, 
# data_frames = [df_aspect, df_canopydensity, df_canopybaseheight, df_canopycover, df_canopyHeight, df_elevation, df_slope, df_observed_48, df_observed_36, df_observed_24, df_observed_12, df_observed_0]
# train = reduce(lambda  left,right: pd.merge(left, right, how='left', left_index=True, right_index=True), data_frames)

In [629]:
#print(X.head(10000))
print(X.shape)

(10000, 5, 30, 30)


In [680]:
df_target_12 = list()
for i in range(10000):
    df_target_12.append(train_data['target'][i][0])

print(len(df_target_12))
print(np.asarray(df_target_12).shape)
#nsamples, nx, ny = np.asarray(df_target_12).shape
#.reshape((nsamples,nx*ny))
Y_train = np.asarray(df_target_12)
#Y_train = Y_train.reshape([-1,1, 30, 30])
print(Y_train.shape)

10000
(10000, 30, 30)
(10000, 30, 30)


In [681]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.calibration import CalibratedClassifierCV

x_train, x_test, y_train, y_test = train_test_split(X, Y_train, test_size = 0.1, random_state = 1)
#x_train, x_cv, y_train, y_cv = train_test_split(x_train, y_train, test_size=0.2)
print(x_train.shape, y_train.shape)
#print(x_cv.shape, y_cv.shape)
print(x_test.shape, y_test.shape)

(9000, 5, 30, 30) (9000, 30, 30)
(1000, 5, 30, 30) (1000, 30, 30)


In [682]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten, Dropout
from keras.layers import concatenate
from keras.layers.convolutional import Conv2D
from keras.optimizers import adadelta,RMSprop,SGD,Adam
from keras.layers.convolutional import MaxPooling2D, AveragePooling2D
import tensorflow as tf

model = Sequential()
model.add(AveragePooling2D())
model.add(Conv2D(filters=4, kernel_size=(3,3), activation='sigmoid', data_format='channels_first'))
model.add(MaxPooling2D(pool_size=2))
model.add(Dropout(0.2))
#model.add(Conv2D(filters=4, kernel_size=3, activation='relu', input_shape=(5,30,30), data_format='channels_first'))
#model.add(MaxPooling2D(pool_size=2))
#model.add(Dropout(0.2))
#model.add(Conv1D(filters=16, kernel_size=3, activation='relu'))
model.compile(optimizer=RMSprop(), loss='categorical_crossentropy', metrics = ['accuracy'])

history = model.fit(x_train, y_train, batch_size= 16, epochs=1)
#model.add(MaxPooling1D(pool_size=2))
#model.add(Flatten())
#model.add(Dense(900, activation='softmax'))

#yhat = model.predict(x_test, verbose=0)
print(model.evaluate(x_test, y_test))
#print(yhat)

ValueError: Error when checking target: expected dropout_19 to have 4 dimensions, but got array with shape (9000, 30, 30)

In [671]:
model.summary()

Model: "sequential_95"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
average_pooling2d_22 (Averag (None, 2, 15, 30)         0         
_________________________________________________________________
conv2d_67 (Conv2D)           (None, 32, 13, 28)        608       
Total params: 608
Trainable params: 608
Non-trainable params: 0
_________________________________________________________________


In [618]:
yhat = model.predict(x_test)
print(y_test[300])
print(yhat[300])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1
 0 0 1 1 1 1 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0
 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 1 0 1 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 1 1 0 0 0 0 0 1 0 0 

In [587]:
model.summary()

Model: "sequential_55"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_24 (Conv2D)           (None, 64, 28, 28)        6976      
_________________________________________________________________
conv2d_25 (Conv2D)           (None, 62, 26, 16)        4048      
_________________________________________________________________
flatten_47 (Flatten)         (None, 25792)             0         
_________________________________________________________________
dense_81 (Dense)             (None, 900)               23213700  
Total params: 23,224,724
Trainable params: 23,224,724
Non-trainable params: 0
_________________________________________________________________


In [487]:
# linear_svc = LinearSVC()
# linear_svc.fit(x_train, y_train)
# y_pred = linear_svc.predict(x_test)
# acc_linear_svc = round(accuracy_score(y_pred, y_test) * 100, 2)
# acc_linear_svc

In [492]:
# alpha = [100,200,500,1000,2000]
# max_depth = [5, 10]
# cv_log_accuracy_array = []
# for i in alpha:
#     for j in max_depth:
#         print("for n_estimators =", i,"and max depth = ", j)
#         clf = RandomForestClassifier(n_estimators=i, criterion='gini', max_depth=j, random_state=42, n_jobs=-1)
#         clf.fit(x_train, y_train)
#         y_cv_pred = clf.predict(x_cv)
#         acc_randomforest = round(accuracy_score(y_cv_pred, y_cv) * 100, 2)
#         cv_log_accuracy_array.append(acc_randomforest)
#         print("Accuracy: ",acc_randomforest)

        

# # randomforest = RandomForestClassifier()
# # randomforest.fit(x_train, y_train)
# # y_pred = randomforest.predict(x_test)
# # acc_randomforest = round(accuracy_score(y_pred, y_test) * 100, 2)
# # print(acc_randomforest)

for n_estimators = 100 and max depth =  5
Accuracy:  13.61
for n_estimators = 100 and max depth =  10
Accuracy:  13.61
for n_estimators = 200 and max depth =  5
Accuracy:  13.61
for n_estimators = 200 and max depth =  10


KeyboardInterrupt: 

In [ ]:
# best_alpha = np.argmin(cv_log_accuracy_array)
# clf = RandomForestClassifier(n_estimators=alpha[int(best_alpha/2)], criterion='gini', max_depth=max_depth[int(best_alpha%2)], random_state=42, n_jobs=-1)
# clf.fit(x_train, y_train)

# predict_y = clf.predict(x_train)
# print('For values of best estimator = ', alpha[int(best_alpha/2)], "The train log loss is:",log_loss(y_train, predict_y, labels=clf.classes_, eps=1e-15))
# predict_y = clf.predict(x_cv)
# print('For values of best estimator = ', alpha[int(best_alpha/2)], "The cross validation log loss is:",log_loss(y_cv, predict_y, labels=clf.classes_, eps=1e-15))
# predict_y = clf.predict(x_test)
# print('For values of best estimator = ', alpha[int(best_alpha/2)], "The test log loss is:",log_loss(y_test, predict_y, labels=clf.classes_, eps=1e-15))